### PR TITLE
added first snapshot mode, quote fixes

### PR DESCRIPTION
**Pull request by iaw**
Wanted to be able to download the first snapshot instead of current snapshot.  Added second mode.

Additionally interior quotes in archive.py were double rather than single in the logging code, adjusted these.

### CODE REVIEW

**Comment by bitdruid** [comment]
thank you for your contribution :) good idea. as i cant try it by myself atm... but can you try to use  `--limit 1` and verify if this would give you the first snapshot of each file? if so i would suggest to implement the functionality over the url 'limit' query-parameter. this would greatly increase download speed because the cdx server will only respond with 1 entry per file instead of all (and filter them afterwards)

**Comment by iaw** [comment]
> edit: sorry took a short look at the manual, limit does hit on the absolute amount.

Just following up here.  Didn't fully follow.  Is there a way to ensure we download only the first snapshot?  Happy to make the modifications, no need to hammer the Internet Archive's bandwidth.

**Comment by bitdruid** [comment]
> > edit: sorry took a short look at the manual, limit does hit on the absolute amount.
> 
> Just following up here. Didn't fully follow. Is there a way to ensure we download only the first snapshot? Happy to make the modifications, no need to hammer the Internet Archive's bandwidth.

i was thinking to far with `--limit`. i studied the API docs again and there seems to be no way to save bandwith... there seems no other way then implementing your approach for now. im reconsidering the change for command `--full`. i may merge and rename them later in dev.

some more words to the cdx-api:
there are some neat features with cuplicate counters i tried to use in the past to save some time with db-filtering but it seems that the api does not provide the features they're mentioning in their docs. [CDX API LINK](https://github.com/internetarchive/wayback/tree/master/wayback-cdx-server)

**Comment by bitdruid** [comment]
i merged your approach and just adapted the formatings a bit. feel free to check out if your intended functionality is still there. i made a short check by downloading snapshots `--all` `--explicit` of one file and compared it to `--first` `--explicit` of the same file. seems to work :)

however i will release when i had a look at #26

**Pull request merged**
